export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const TOTAL = "TOTAL";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const UPDATE_CHARITIES = 'UPDATE_CHARITIES';
export const UPDATE_CURRENT_CHARITY = "UPDATE_CURRENT_CHARITY";
export const UPDATE_CHARITY_PRODUCTS = "UPDATE_CHARITY_PRODUCTS";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const EMPTY_CART = "EMPTY_CART";
export const ORDER_SUMMARY = "ORDER_SUMMARY";
export const FAVORITE_CHARITY = "FAVORITE_CHARITY";

